### ISSUE TITLE
Automatic formatting of disks

### ISSUE THREAD

**Issue by keeleysam** [grahamgilbert/imagr#115]
Currently imagr can only run if there is a partition that can be restored to, but this is not always the case.  If you have a corrupted filesystem, no HFS partitions, some encrypted disks, etc, it will not be able to run.

It also must exist when imagr launches, so if you want to hack around this you have to partition before launching.

DeployStudio has a function to format disks, most people use the "First disk available" option which works quite well on the vast majority of machines, though having multiple disks such as with a Fusion Drive can trip it up a bit.

Instead of choosing a volume to run a workflow on, I'd like to have a workflow type where the volume is undeclared and imagr wipes the disk and then restores onto the fresh disk.  This could probably be made intelligent to skip external drives and perhaps setup fusion drives automatically.

It is definitely useful to be able to choose volumes, especially if you are using imagr with machines in target disk mode.  However, I've seen a lot of machines where imagr cannot properly run as they have no volumes.

**Comment by grahamgilbert** [comment]
That all sounds fine in principle, but how do you determine the first disk? Pick a random one? We currently use gpymacutil for disk handling, so if we have to move from that, we'll need to rewrite a fair bit of Imagr.

**Comment by calum-github** [comment]
I'd also like to chime in here and suggest the check for a writeable volume at imagr launch could be a little bit premature in some setups, suppose we have a script that formats/partitions a volume into the correct configuration as part of a workflow but prior to a dmg being restored to that volume.

For example, currently I run a script in deploy studio to deal with fusion drives and drives that have FV encryption enabled

https://gist.github.com/hunty1/b3252e2604cf32f031ef57382a868265

I would run this script before any restore task in a workflow to ensure that the DMG is restored to the correct volume and that the disk is partitioned/fusion'd correctly.

If Imagr runs on a machine with a corrupt or unintialised drive, then it throws a warning message immediately rather than allowing any admin created scripts to deal with this situation first.

Perhaps the error about non writeable volumes could be moved to occur only prior to a restore task in a workflow? Or perhaps a plist item to disable the writeable volume check at launch?

I guess this would also mean that you would need to allow a target volume to be specified in the workflow also

Hmm food for thought

**Comment by grahamgilbert** [comment]
Correct, this isn't quite as simple as it seems. I guess if there is only one disk attached (which is pretty common I assume) we could just wait until the workflow starts. Open to ideas on this.

**Comment by erikng** [comment]
I like that idea. I think it's pretty safe and allows an admin to fully automate a workflow (apart from holding down N).

On Oct 16, 2016, at 3:03 AM, Graham Gilbert <notifications@github.com<mailto:notifications@github.com>> wrote:

Correct, this isn't quite as simple as it seems. I guess if there is only one disk attached (which is pretty common I assume) we could just wait until the workflow starts. Open to ideas on this.

> On 28 Sep 2016, at 02:26, Calum <notifications@github.com<mailto:notifications@github.com>> wrote:
> 
> I'd also like to chime in here and suggest the check for a writeable volume at imagr launch could be a little bit premature in some setups, suppose we have a script that formats/partitions a volume into the correct configuration as part of a workflow but prior to a dmg being restored to that volume.
> 
> For example, currently I run a script in deploy studio to deal with fusion drives and drives that have FV encryption enabled
> 
> https://gist.github.com/hunty1/b3252e2604cf32f031ef57382a868265
> 
> I would run this script before any restore task in a workflow to ensure that the DMG is restored to the correct volume and that the disk is partitioned/fusion'd correctly.
> 
> If Imagr runs on a machine with a corrupt or unintialised drive, then it throws a warning message immediately rather than allowing any admin created scripts to deal with this situation first.
> 
> Perhaps the error about non writeable volumes could be moved to occur only prior to a restore task in a workflow? Or perhaps a plist item to disable the writeable volume check at launch?
> 
> I guess this would also mean that you would need to allow a target volume to be specified in the workflow also
> 
> Hmm food for thought
> 
> ## 
> 
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

##

**Comment by grahamgilbert** [comment]
18 months old, closing this unless there is a burning desire to re-open.
