### ISSUE TITLE
Imagr crashes if reporting server unavailable

### ISSUE THREAD

**Issue by calum-github** [grahamgilbert/imagr#168]
### Description of Issue/Question
When I have Imagr v1.3.8 setup to talk to a imagr_server reporting dashboard and that dashboard is unavailable. Imagr crashes on launch

### Setup
macOS 10.12.2 NBI created with AutoImagrNBI v1.3.4

### Steps to Reproduce Issue
configure reporting server in plist (attached a copy of the plist)
ensure that reporting server is offline
launch imagr, note that it crashes
review crash log (attached)

To confirm this is the cause of the crash i removed the reporting URL and key from the com.grahamgilbert.imagr.plist and then launched imagr again. No problems encountered

### Versions Report
as mentioned above imagr 1.3.8 with AutoImagrNBI v 1.3.4

[crash.txt](https://github.com/grahamgilbert/imagr/files/662825/crash.txt)

[com.grahamgilbert.Imagr.txt](https://github.com/grahamgilbert/imagr/files/662826/com.grahamgilbert.Imagr.txt)

**Comment by pudquick** [comment]
I'm unable to replicate.

Rather than crashing when the reporting server is offline, I get these results:

If the server pings, but is not responding on port 80, I get:
`2016-12-27 17:14:00.220 Imagr[37262:470836] Download error -1004: Could not connect to the server.`

If the server does not ping / is not online at all, I get:
`2016-12-27 17:16:10.211 Imagr[37405:473198] Download error -1001: The request timed out.`

But otherwise the app continues on as normal / does not crash at launch.

**Comment by calum-github** [comment]
Yep it was on my end, my bad
