### ISSUE TITLE
Config plist validation

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/imagr#33]
If the configuration plist is not properly formatted, Imagr will crash. Should validate and present an error message.
- [x] tag validation 16fb581fb2d801d4b0d11769cbb6bcf74092a190
- [x] two workflows with same name 55be9d4da2f398334b87090eb5a7e41e1d18e02a
- [x] Currently possible to have multiple `password` keys (see comment below)

**Comment by clburlison** [comment]
I'm not sure if Github sends a message when a previous issue is edited. I've updated the original to update the status of this issue as validation is now present.

**Comment by grahamgilbert** [comment]
Yes, you _can_ have more than one `password` key, but only the bottom most one will be used. Let's say we have loaded the configuration plist into the variable, `config`. What we're effectively doing is setting `config['password']` and then setting `config['password']` again. I set the `password` twice in my config plist and then ran this bit of python:

``` python
import FoundationPlist

config = FoundationPlist.readPlist(plist)

for key in config:
    print key

```

And I got

```
password
workflows
```

**Comment by clburlison** [comment]
Alright, that doesn't sound like a show stopper to me. Unless someone else can find something else that breaks the validation process I believe the new script solves this issue.

**Comment by gregneagle** [comment]
"Yes, you can have more than one password key, but only the bottom most one will be used."

It's probably safer to say that which one will be actually used is undefined. It appears that the CoreFoundation plist parser currently behaves as you've described (processing keys and values in order, so that a later key with the same name as a previous key would cause the key's value to be replaced), but no-one should count on this behavior.
