### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by erikng** [grahamgilbert/imagr#59]
It would be nice if new workflows could be viewed without quitting Imagr.

**Comment by natewalck** [comment]
Brainstorming on this one.

Perhaps allow Command-R to refresh the screen?

Maybe a small refresh button near the main workflow screen. This would probably be the easiest UI to implement.

**Comment by gregneagle** [comment]
You want to be careful: it won't always be appropriate to refresh workflows, and the "get the current configuration.plist" code probably needs to be refactored to be able to be called from other contexts. Since it happens in a secondary thread, also need to be careful that someone could not trigger a second instance before a (first) instance completes.

**Comment by grahamgilbert** [comment]
Yes, the load data bits will need re-working. That's been on my todo list anyway, so this is a good opportunity.

**Comment by erikng** [comment]
Why close this if its not completed? I (and probably others) don't religiously look at the commit log.

I have other enhancements that I would like to mark for visibility/discussion but if they will just be closed I won't waste my time.

**Comment by grahamgilbert** [comment]
It **is** completed. Notice the referenced commit.

![screenshot 2015-05-01 12 46 39](https://cloud.githubusercontent.com/assets/1208495/7429800/2a415ae0-f000-11e4-9d11-7f3ee42c1a7c.png)

**Comment by erikng** [comment]
Phone didn't show it. My apologies.

**Comment by gregneagle** [comment]
GitHub emails don't show the referenced commits; I didn't see them until I checked GitHub itself. Moral: use the emails as notifications, but always check GitHub for the details.
