### ISSUE TITLE
Disable network check on first boot

### ISSUE THREAD

**Issue by grahamgilbert** [grahamgilbert/imagr#73]
The first boot script will wait for the network to be available before installing anything. The [source script](https://github.com/grahamgilbert/first-boot-pkg) allows for this to be disabled, so we need to have a key in the workflow to let this be disabled.

**Comment by clburlison** [comment]
I know this hasn't come up often but it's still something that I'd like and it's a pretty easy enhancement. I wanted your thoughts before I made a PR.
- Does this need to be modifiable at the root level of the config or per workflow? I can see reasoning for both.
- While making the change, I might as well make the `retry_count` configurable as well?
- Should the Network Wait default be `False` instead of `True`? That's a recent change you made https://github.com/grahamgilbert/first-boot-pkg/commit/cd4dc56646d4dd8a1c4e9717e017e8d7cebba1dd and I agree that it should be moved over to Imagr.

Cheers, 
Clayton

**Comment by chilcote** [comment]
Default to True. I learned that lesson recently. https://github.com/chilcote/outset/commit/52ffcc24c372174d668588219269c2b0c174f166

**Comment by grahamgilbert** [comment]
Modifiable per workflow please. 
Might as well do the retry count too. 
Leave it as what it is now (to wait for the network) as a default. 
Sent from my iPhone

On Tue, May 24, 2016 at 10:31 PM -0700, "Joseph Chilcote" notifications@github.com wrote:

Default to True. I learned that lesson recently. chilcote/outset@52ffcc2
